# Generated by Django 5.0.3 on 2024-06-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='declared_order_duration',
            field=models.IntegerField(),
        ),
    ]
